# .github/workflows/gitcompare.yml
name: GitCompare by Comment

on:
  issue_comment:
    types: [created]

jobs:
  comment_trigger:
    runs-on: ubuntu-latest

    # Run whenever the comment mentions "/gitcompare" anywhere
    if: contains(github.event.comment.body, '/gitcompare')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract GOOD_BUILD and BAD_BUILD from comment
        id: parse_comment
        run: |
          # Grab the full comment
          COMMENT="${{ github.event.comment.body }}"

          # Remove Markdown code fences (``` lines)
          CLEANED="$(printf '%s\n' "$COMMENT" \
            | sed '/^```/d')"

          # Remove any leading text up to /gitcompare
          CLEANED="${CLEANED#*\/gitcompare}"

          # Now split on the literal '---' delimiter
          GOOD="$(printf '%s\n' "$CLEANED" \
            | sed -n '1,/^---$/p' \
            | sed '1d' \
            | sed '/^[[:space:]]*$/d')"
          BAD="$(printf '%s\n' "$CLEANED" \
            | sed -n '1,/^---$/d' \
            | sed '/^[[:space:]]*$/d')"

          echo "=== DEBUG: GOOD_BUILD ==="
          echo "$GOOD"
          echo "=== DEBUG: BAD_BUILD ==="
          echo "$BAD"
          echo "=========================="

          # Export to environment for next step
          echo "GOOD_BUILD<<EOF" >> $GITHUB_ENV
          echo "$GOOD"            >> $GITHUB_ENV
          echo "EOF"              >> $GITHUB_ENV
          echo "BAD_BUILD<<EOF"   >> $GITHUB_ENV
          echo "$BAD"             >> $GITHUB_ENV
          echo "EOF"              >> $GITHUB_ENV

      - name: Make commit_hunter.sh executable
        run: chmod +x .github/scripts/commit_hunter.sh

      - name: Run commit_hunter.sh and print compare URLs
        run: ./.github/scripts/commit_hunter.sh "$GOOD_BUILD" "$BAD_BUILD"
