- name: Parse comment
  id: parse
  env:
    COMMENT_BODY: ${{ github.event.comment.body }}
  run: |
    chmod +x ./scripts/parse_comment.sh
    ./scripts/parse_comment.sh "$COMMENT_BODY"

...

- name: Parse URLs from output
  id: parse_urls
  run: |
    chmod +x ./scripts/parse_urls.sh
    ./scripts/parse_urls.sh

...

- name: Comment on PR
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GITHUB_REPOSITORY: ${{ github.repository }}
    ISSUE_NUMBER: ${{ github.event.issue.number }}
  run: |
    pip install PyGithub
    python3 ./scripts/post_comment.py
