# .github/workflows/gitcompare.yml
name: GitCompare by Comment

on:
  issue_comment:
    types: [created]

jobs:
  comment_trigger:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/gitcompare')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract GOOD_BUILD and BAD_BUILD from comment
        id: parse_comment
        run: |
          COMMENT="${{ github.event.comment.body }}"
          BODY="$(printf '%s\n' "$COMMENT" | tail -n +2)"
          GOOD="$(printf '%s\n' "$BODY" | sed -n '1,/^---$/p' | sed '1d')"
          BAD="$(printf '%s\n' "$BODY" | sed -n '1,/^---$/d')"
          GOOD="$(printf '%s\n' "$GOOD" | sed '/^[[:space:]]*$/d')"
          BAD="$(printf '%s\n' "$BAD"  | sed '/^[[:space:]]*$/d')"
          echo "GOOD_BUILD<<EOF" >> $GITHUB_ENV
          echo "$GOOD"            >> $GITHUB_ENV
          echo "EOF"              >> $GITHUB_ENV
          echo "BAD_BUILD<<EOF"   >> $GITHUB_ENV
          echo "$BAD"             >> $GITHUB_ENV
          echo "EOF"              >> $GITHUB_ENV

      - name: Make parsing script executable
        run: chmod +x .github/scripts/commit_hunter.sh

      - name: Run commit_hunter.sh and print compare URLs
        run: |
          ./.github/scripts/commit_hunter.sh "$GOOD_BUILD" "$BAD_BUILD"
